In [1]:
# import libraries
import pandas as pd
import numpy as np

In [2]:
#step 2- Reading the dataset
dataset = pd.read_csv(r"datasets_12204_16735_WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset.isnull().any()

Age                         False
Attrition                   False
BusinessTravel              False
DailyRate                   False
Department                  False
DistanceFromHome            False
Education                   False
EducationField              False
EmployeeCount               False
EmployeeNumber              False
EnvironmentSatisfaction     False
Gender                      False
HourlyRate                  False
JobInvolvement              False
JobLevel                    False
JobRole                     False
JobSatisfaction             False
MaritalStatus               False
MonthlyIncome               False
MonthlyRate                 False
NumCompaniesWorked          False
Over18                      False
OverTime                    False
PercentSalaryHike           False
PerformanceRating           False
RelationshipSatisfaction    False
StandardHours               False
StockOptionLevel            False
TotalWorkingYears           False
TrainingTimesL

In [5]:
dataset

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1   
1                    8          1  Life Sciences              1   
2                    2          2          Other              1   
3                    3          4  Life Sciences              1   
4                    2          1        Medical              1   
...                ...        ...            ...            ...   
1465                23          2        Medical              1   
1466                 6          1        Medical              1   
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80   
1                  2  ...                         4            80   
2                  4  ...                         2            80   
3                  5  ...                         3            80   
4                  7  ...                         4            80   
...              ...  ...                       ...           ...   
1465            2061  ...                         3            80   
1466            2062  ...                         1            80   
1467            2064  ...                         2            80   
1468            2065  ...                         4            80   
1469            2068  ...                         1            80   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0   
1                    1                 10                      3   
2                    0                  7                      3   
3                    0                  8                      3   
4                    1                  6                      3   
...                ...                ...                    ...   
1465                 1                 17                      3   
1466                 1                  9                      5   
1467                 1                  6                      0   
1468                 0                 17                      3   
1469                 0                  6                      3   

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4   
1                  3              10                  7   
2                  3               0                  0   
3                  3               8                  7   
4                  3               2                  2   
...              ...             ...                ...   
1465               3               5                  2   
1466               3               7                  7   
1467               3               6                  2   
1468               2               9    

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['EducationField'] = le.fit_transform(dataset['EducationField'])

In [7]:
dataset.head(10)

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   
5   32        No  Travel_Frequently       1005  Research & Development   
6   59        No      Travel_Rarely       1324  Research & Development   
7   30        No      Travel_Rarely       1358  Research & Development   
8   38        No  Travel_Frequently        216  Research & Development   
9   36        No      Travel_Rarely       1299  Research & Development   

   DistanceFromHome  Education  EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2               1              1               1   
1                 8          1               1              1               2   
2                 2          2               4              1               4   
3                 3          4               1              1               5   
4                 2          1               3              1               7   
5                 2          2               1              1               8   
6                 3          3               3              1              10   
7                24          1               1              1              11   
8                23          3               1              1              12   
9                27          3               3              1              13   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   
5  ...                         3            80                 0   
6  ...                         1            80                 3   
7  ...                         2            80                 1   
8  ...                         2            80                 0   
9  ...                         2            80                 2   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   
5                  8                      2               2               7   
6                 12                      3               2               1   
7                  1                      2               3               1   
8                 10                      2               3               9   
9                 17                      3               2               7   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  
5                  7                        3                     6  
6                  0                        0                     0  
7                  0                        0                     0  
8                  7                        1  

In [8]:
dataset.corr()

Age  DailyRate  DistanceFromHome  Education  \
Age                       1.000000   0.010661         -0.001686   0.208034   
DailyRate                 0.010661   1.000000         -0.004985  -0.016806   
DistanceFromHome         -0.001686  -0.004985          1.000000   0.021042   
Education                 0.208034  -0.016806          0.021042   1.000000   
EducationField           -0.040873   0.037709          0.002013  -0.039592   
EmployeeCount                  NaN        NaN               NaN        NaN   
EmployeeNumber           -0.010145  -0.050990          0.032916   0.042070   
EnvironmentSatisfaction   0.010146   0.018355         -0.016075  -0.027128   
HourlyRate                0.024287   0.023381          0.031131   0.016775   
JobInvolvement            0.029820   0.046135          0.008783   0.042438   
JobLevel                  0.509604   0.002966          0.005303   0.101589   
JobSatisfaction          -0.004892   0.030571         -0.003669  -0.011296   
MonthlyIncome             0.497855   0.007707         -0.017014   0.094961   
MonthlyRate               0.028051  -0.032182          0.027473  -0.026084   
NumCompaniesWorked        0.299635   0.038153         -0.029251   0.126317   
PercentSalaryHike         0.003634   0.022704          0.040235  -0.011111   
PerformanceRating         0.001904   0.000473          0.027110  -0.024539   
RelationshipSatisfaction  0.053535   0.007846          0.006557  -0.009118   
StandardHours                  NaN        NaN               NaN        NaN   
StockOptionLevel          0.037510   0.042143          0.044872   0.018422   
TotalWorkingYears         0.680381   0.014515          0.004628   0.148280   
TrainingTimesLastYear    -0.019621   0.002453         -0.036942  -0.025100   
WorkLifeBalance          -0.021490  -0.037848         -0.026556   0.009819   
YearsAtCompany            0.311309  -0.034055          0.009508   0.069114   
YearsInCurrentRole        0.212901   0.009932          0.018845   0.060236   
YearsSinceLastPromotion   0.216513  -0.033229          0.010029   0.054254   
YearsWithCurrManager      0.202089  -0.026363          0.014406   0.069065   

                          EducationField  EmployeeCount  EmployeeNumber  \
Age                            -0.040873            NaN       -0.010145   
DailyRate                       0.037709            NaN       -0.050990   
DistanceFromHome                0.002013            NaN        0.032916   
Education                      -0.039592            NaN        0.042070   
EducationField                  1.000000            NaN       -0.002516   
EmployeeCount                        NaN            NaN             NaN   
EmployeeNumber                 -0.002516            NaN        1.000000   
EnvironmentSatisfaction         0.043163            NaN        0.017621   
HourlyRate                     -0.021941            NaN        0.035179   
JobInvolvement                 -0.002655            NaN       -0.006888   
JobLevel                       -0.044933            NaN       -0.018519   
JobSatisfaction                -0.034401            NaN       -0.046247   
MonthlyIncome                  -0.041070            NaN       -0.014829   
MonthlyRate                    -0.027182            NaN        0.012648   
NumCompaniesWorked             -0.008663            NaN       -0.001251   
PercentSalaryHike              -0.011214            NaN       -0.012944   
PerformanceRating              -0.005614            NaN       -0.020359   
RelationshipSatisfaction       -0.004378            NaN       -0.069861   
StandardHours                        NaN            NaN             NaN   
StockOptionLevel               -0.016185            NaN        0.062227   
TotalWorkingYears              -0.027848            NaN       -0.014365   
TrainingTimesLastYear           0.049195            NaN        0.023603   
WorkLifeBalance                 0.041191            NaN        0.010309   
YearsAtCompany                 -0.018692      

In [9]:
x = dataset.iloc[:,:].values

In [10]:
y = dataset.iloc[:,:].values

In [11]:
x

array([[41, 'Yes', 'Travel_Rarely', ..., 4, 0, 5],
       [49, 'No', 'Travel_Frequently', ..., 7, 1, 7],
       [37, 'Yes', 'Travel_Rarely', ..., 0, 0, 0],
       ...,
       [27, 'No', 'Travel_Rarely', ..., 2, 0, 3],
       [49, 'No', 'Travel_Frequently', ..., 6, 0, 8],
       [34, 'No', 'Travel_Rarely', ..., 3, 1, 2]], dtype=object)

In [12]:
y

array([[41, 'Yes', 'Travel_Rarely', ..., 4, 0, 5],
       [49, 'No', 'Travel_Frequently', ..., 7, 1, 7],
       [37, 'Yes', 'Travel_Rarely', ..., 0, 0, 0],
       ...,
       [27, 'No', 'Travel_Rarely', ..., 2, 0, 3],
       [49, 'No', 'Travel_Frequently', ..., 6, 0, 8],
       [34, 'No', 'Travel_Rarely', ..., 3, 1, 2]], dtype=object)

In [13]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z = one.fit_transform(x).toarray()

In [14]:
z

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
x=one.fit_transform(x).toarray()

In [16]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
x.shape


(1470, 5506)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [19]:
y_test.shape

(294, 35)

In [20]:
x_train.shape

(1176, 5506)

In [21]:
y_train.shape

(1176, 35)

In [22]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
x_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [24]:
dataset.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education  EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2               1              1               1   
1                 8          1               1              1               2   
2                 2          2               4              1               4   
3                 3          4               1              1               5   
4                 2          1               3              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

In [25]:
dataset['BusinessTravel'].fillna(dataset['BusinessTravel'].mode()[0], inplace =True)
dataset['Attrition'].fillna(dataset['Attrition'].mode()[0], inplace =True)
dataset['DailyRate'].fillna(dataset['DailyRate'].median(), inplace =True)
dataset['EducationField'].fillna(dataset['EducationField'].median(), inplace =True) 

In [26]:
dataset.isnull().any()

Age                         False
Attrition                   False
BusinessTravel              False
DailyRate                   False
Department                  False
DistanceFromHome            False
Education                   False
EducationField              False
EmployeeCount               False
EmployeeNumber              False
EnvironmentSatisfaction     False
Gender                      False
HourlyRate                  False
JobInvolvement              False
JobLevel                    False
JobRole                     False
JobSatisfaction             False
MaritalStatus               False
MonthlyIncome               False
MonthlyRate                 False
NumCompaniesWorked          False
Over18                      False
OverTime                    False
PercentSalaryHike           False
PerformanceRating           False
RelationshipSatisfaction    False
StandardHours               False
StockOptionLevel            False
TotalWorkingYears           False
TrainingTimesL

In [27]:
dataset.drop(['EnvironmentSatisfaction','Gender','JobInvolvement','HourlyRate','JobInvolvement','JobLevel'], axis = 1,inplace = True)

In [28]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
dataset['Age']=le.fit_transform(dataset['Age'])
dataset['Attrition']=le.fit_transform(dataset['Attrition'])
dataset['Department']=le.fit_transform(dataset['Department'])
dataset['DistanceFromHome']=le.fit_transform(dataset['DistanceFromHome'])
dataset['EducationField']=le.fit_transform(dataset['EducationField'])
dataset['EmployeeCount']=le.fit_transform(dataset['EmployeeCount'])
dataset['EmployeeNumber']=le.fit_transform(dataset['EmployeeNumber'])
dataset['JobRole']=le.fit_transform(dataset['JobRole'])
dataset['JobSatisfaction']=le.fit_transform(dataset['JobSatisfaction'])
dataset['MaritalStatus']=le.fit_transform(dataset['MaritalStatus'])
dataset['MonthlyIncome']=le.fit_transform(dataset['MonthlyIncome'])
dataset['MonthlyRate']=le.fit_transform(dataset['MonthlyRate'])
dataset['NumCompaniesWorked']=le.fit_transform(dataset['NumCompaniesWorked'])
dataset['Over18']=le.fit_transform(dataset['Over18'])
dataset['OverTime']=le.fit_transform(dataset['OverTime'])
dataset['PercentSalaryHike']=le.fit_transform(dataset['PercentSalaryHike'])
dataset['PerformanceRating']=le.fit_transform(dataset['PerformanceRating'])
dataset['RelationshipSatisfaction']=le.fit_transform(dataset['RelationshipSatisfaction'])
dataset['StandardHours']=le.fit_transform(dataset['StandardHours'])
dataset['StockOptionLevel']=le.fit_transform(dataset['StockOptionLevel'])
dataset['TotalWorkingYears']=le.fit_transform(dataset['TotalWorkingYears'])
dataset['TrainingTimesLastYear']=le.fit_transform(dataset['TrainingTimesLastYear'])
dataset['WorkLifeBalance']=le.fit_transform(dataset['WorkLifeBalance'])
dataset['YearsAtCompany']=le.fit_transform(dataset['YearsAtCompany'])
dataset['YearsInCurrentRole']=le.fit_transform(dataset['YearsInCurrentRole'])
dataset['YearsSinceLastPromotion']=le.fit_transform(dataset['YearsSinceLastPromotion'])
dataset['YearsWithCurrManager']=le.fit_transform(dataset['YearsWithCurrManager'])
dataset.head()

Age  Attrition     BusinessTravel  DailyRate  Department  DistanceFromHome  \
0   23          1      Travel_Rarely       1102           2                 0   
1   31          0  Travel_Frequently        279           1                 7   
2   19          1      Travel_Rarely       1373           1                 1   
3   15          0  Travel_Frequently       1392           1                 2   
4    9          0      Travel_Rarely        591           1                 1   

   Education  EducationField  EmployeeCount  EmployeeNumber  ...  \
0          2               1              0               0  ...   
1          1               1              0               1  ...   
2          2               4              0               2  ...   
3          4               1              0               3  ...   
4          1               3              0               4  ...   

   RelationshipSatisfaction  StandardHours  StockOptionLevel  \
0                         0              0                 0   
1                         3              0                 1   
2                         1              0                 0   
3                         2              0                 0   
4                         3              0                 1   

   TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
0                  8                      0                0               6   
1                 10                      3                2              10   
2                  7                      3                2               0   
3                  8                      3                2               8   
4                  6                      3                2               2   

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                   4                        0                     5  
1                   7                        1                     7  
2                   0                        0                     0  
3                   7                        3                     0  
4                   2                        2                     2  

[5 rows x 30 columns]

In [43]:
x = dataset.iloc[:,5:9].values
y = dataset.iloc[:,9:10].values

In [44]:
y.shape

(1470, 1)

In [45]:
x.shape

(1470, 4)

In [46]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [47]:
x_train

array([[20,  3,  1,  0],
       [27,  3,  5,  0],
       [25,  3,  2,  0],
       ...,
       [ 1,  3,  3,  0],
       [ 1,  5,  3,  0],
       [ 9,  4,  2,  0]], dtype=int64)

In [48]:
y_train

array([[1374],
       [1092],
       [ 768],
       ...,
       [1216],
       [ 559],
       [ 684]], dtype=int64)

In [49]:
from sklearn.tree import DecisionTreeClassifier
drc = DecisionTreeClassifier (criterion = 'entropy',random_state = 0)
drc.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [50]:
drc

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [51]:
x

array([[0, 2, 1, 0],
       [7, 1, 1, 0],
       [1, 2, 4, 0],
       ...,
       [3, 3, 1, 0],
       [1, 3, 3, 0],
       [7, 3, 3, 0]], dtype=int64)

In [52]:
y_pred  = drc.predict(x_test)

In [53]:
y_pred

array([  98,   42,  201,  697,  163,    6,  759,   37,   73,  166, 1297,
         99,  188,    0, 1297,   41,  118,  118, 1320, 1388,  179,   83,
        245,  252,   99,  677,  636,   71, 1152,  495,   95,  188,  207,
         28, 1320,  245,  451,   20,   32,  201,  756,  937,  250,  115,
         44,   16,  146,  188,  250,   60,  252, 1082,  691,  151,   71,
        214,  174,  677,  549,  151,   71,  949,   95,   73,  150,  214,
         41,  756,   21, 1029,  775,   99,  132, 1063,  158,  160,  179,
         71,   71,  387,  174,  677,  625,   73, 1297,   33,  532,    0,
        118, 1324,  185, 1151,  628,   67,  250,  438,  832, 1289,  314,
        104,  937,  352, 1184, 1132,  788,   30,   74,  147,  271,  562,
         17,  135,   72, 1320,   69,  290,   70,   74,  640,  115,  824,
         41,   16,  286,    0,   30,  188,  289,   67, 1022,  370,   21,
        592,  193,   67,   83,  292,  135,  518,  612,   77,  290,  677,
         70,  415,   59,   71,  796,  118,  172,   

In [54]:
y_test

array([[ 442],
       [1091],
       [ 981],
       [ 785],
       [1332],
       [ 501],
       [1058],
       [1253],
       [ 751],
       [ 122],
       [ 268],
       [ 940],
       [1125],
       [ 540],
       [1034],
       [ 432],
       [ 794],
       [ 666],
       [ 942],
       [1114],
       [ 853],
       [1330],
       [ 692],
       [ 548],
       [  54],
       [ 319],
       [1147],
       [1235],
       [1436],
       [ 520],
       [ 983],
       [1347],
       [ 465],
       [ 966],
       [  31],
       [ 420],
       [1462],
       [1408],
       [  89],
       [ 298],
       [ 875],
       [1385],
       [1430],
       [ 223],
       [1412],
       [1375],
       [   4],
       [1174],
       [ 892],
       [  34],
       [1310],
       [ 182],
       [ 467],
       [  52],
       [1032],
       [ 142],
       [1440],
       [ 528],
       [ 629],
       [1051],
       [1269],
       [ 993],
       [ 526],
       [ 278],
       [ 887],
       [1275],
       [ 6

In [55]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [56]:
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)